#!/bin/sh

echo "This script is going to install several suckless utilities and write their files to your .config directory. 
If you have directories .config/surf, .config/dmenu, .config/dwm etc. they will be gone.
You can only run this script as a user, never as root -- otherwize the script is going to fail.
Do you wish to proceed? [Y/n] 
WARNING: DO NOT END THIS SCRIPT BY PRESSING CTRL+C AS YOUR icanon SETTINGS WILL BE ALTERED. ONLY EXIT BY PRESSING n" 

saved_tty_settings=$(stty -g)
stty -icanon min 1 time 0

while true
do
  input=$(head -c 1) 
  echo ""

	case $input in
	    [yY])
            # Install libxft-bgra for the emojis not to crash dwmblocks

            mkdir ~/.config

            echo "First, we have to configure your dwmblocks"
            dwmblocks_config="$(cat dwmblocks_defconf)"

            echo "Do you want volume to be in your dwmblocks [Y/n]"
            while true
            do 
              input=$(head -c 1)
              echo ""
              case $input in 
                [yY])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s/VOLUME/{\"🔊\", \"pamixer --get-volume-human\",	5,	10},")
                  break
                  ;;
                [nN])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s/VOLUME/\/\/{\"🔊\", \"pamixer --get-volume-human\",	5,	10},")
                  break
                  ;;
                *)
                  echo "Invalid input"
                  ;;
              esac
            done

            echo "Do you want layout to be in your dwmblocks [Y/n]"
            while true
            do 
              input=$(head -c 1)
              echo ""
              case $input in 
                [yY])
                  pacaur -S xkblayout-state-git
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s/KEYBOARD/{\"🎹\", \"xkblayout-state print '%n'\",	1,		0},/")
                  break
                  ;;
                [nN])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s/KEYBOARD/\/\/{\"🎹\", \"xkblayout-state print '%n'\",	1,		0},/")
                  break
                  ;;
                *)
                  echo "Invalid input"
                  ;;
              esac
            done

            echo "Do you want RAM to be in your dwmblocks [Y/n]"
            while true
            do 
              input=$(head -c 1)
              echo ""
              case $input in 
                [yY])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s/RAM/{\"💾\", \"free -h | awk '\/^Mem\/ { print \$3\\\\\"\/\\\\\"\$2 }' | sed s\/i\/\/g\",	10,	0},/")
                  break
                  ;;
                [nN])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s/RAM/\/\/{\"💾\", \"free -h | awk '\/^Mem\/ { print \$3\\\\\"\/\\\\\"\$2 }' | sed s\/i\/\/g\",	10,	0},/")
                  break
                  ;;
                *)
                  echo "Invalid input"
                  ;;
              esac
            done

            echo "Do you want CPU temperature to be in your dwmblocks [Y/n]"
            while true
            do 
              input=$(head -c 1)
              echo ""
              case $input in 
                [yY])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s/CPUTEMP/{\"🌡\", \"cputemp\",	5,	0},/")
                  break
                  ;;
                [nN])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s/CPUTEMP/\/\/{\"🌡\", \"cputemp\",	5,	0},/")
                  break
                  ;;
                *)
                  echo "Invalid input"
                  ;;
              esac
            done

            echo "Do you want your GPU temperature to be in your dwmblocks [Y/n]"
            while true
            do 
              input=$(head -c 1)
              echo ""
              case $input in 
                [yY])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s/GPUTEMP/{\"🌡\", \"gputemp\",	5,	0},/")
                  break
                  ;;
                [nN])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s/GPUTEMP/\/\/{\"🌡\", \"gputemp\",	5,	0},/")
                  break
                  ;;
                *)
                  echo "Invalid input"
                  ;;
              esac
            done

            echo "Do you want  to be in your dwmblocks [Y/n]"
            while true
            do 
              input=$(head -c 1)
              echo ""
              case $input in 
                [yY])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s//{},/")
                  break
                  ;;
                [nN])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s//\/\/{},/")
                  break
                  ;;
                *)
                  echo "Invalid input"
                  ;;
              esac
            done

            echo "Do you want  to be in your dwmblocks [Y/n]"
            while true
            do 
              input=$(head -c 1)
              echo ""
              case $input in 
                [yY])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s//{},/")
                  break
                  ;;
                [nN])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s//\/\/{},/")
                  break
                  ;;
                *)
                  echo "Invalid input"
                  ;;
              esac
            done

            echo "Do you want  to be in your dwmblocks [Y/n]"
            while true
            do 
              input=$(head -c 1)
              echo ""
              case $input in 
                [yY])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s//{},/")
                  break
                  ;;
                [nN])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s//\/\/{},/")
                  break
                  ;;
                *)
                  echo "Invalid input"
                  ;;
              esac
            done

            echo "Do you want  to be in your dwmblocks [Y/n]"
            while true
            do 
              input=$(head -c 1)
              echo ""
              case $input in 
                [yY])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s//{},/")
                  break
                  ;;
                [nN])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s//\/\/{},/")
                  break
                  ;;
                *)
                  echo "Invalid input"
                  ;;
              esac
            done

            echo "Do you want  to be in your dwmblocks [Y/n]"
            while true
            do 
              input=$(head -c 1)
              echo ""
              case $input in 
                [yY])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s//{},/")
                  break
                  ;;
                [nN])
                  dwmblocks_config=$(echo "$dwmblocks_config" | sed "s//\/\/{},/")
                  break
                  ;;
                *)
                  echo "Invalid input"
                  ;;
              esac
            done

            echo "Proceeding to install the dependencies" &&

            # Import gpg key to authorize libxft-bgra
            gpg --keyserver pool.sks-keyservers.net --recv-key CFDF148828C642A7 &&

            git clone https://aur.archlinux.org/libxft-bgra.git &&
            cd libxft-bgra &&
            makepkg -si
            cd .. &&
            rm -Rf libxft-bgra &&

            echo "Suckless tools' installation is initiated" &&

            # Install the suckless software
            #dwm
            cd dwm &&
            sudo make install &&
            cd .. &&
            cp -r dwm ~/.config/ &&

            #dmenu
            cd dmenu &&
            sudo make install &&
            cd .. &&
            cp -r dmenu ~/config/ &&

            #st
            cd st &&
            sudo make install &&
            cd .. &&
            cp -r st ~/config/ &&

            #dwmblocks
            cd dwmblocks &&
            sudo make install &&
            cd .. &&
            cp -r dwmblocks ~/config/ &&

            #slock
            cd slock &&
            sudo make install &&
            cd .. &&
            cp -r slock ~/config/ &&

            #surf
            cd surf &&
            sudo make install &&
            cd .. &&
            cp -r surf ~/.config/ &&

            #tabbed
            cd tabbed &&
            sudo make install &&
            cd .. &&
            cp -r tabbed ~/.config/ &&

            #scripts
            sudo cp scripts/bin/* /usr/local/bin/ &&

            echo "Installation was successfully completed" &&
            break ||
            echo "There was an ERROR while installing some of the utilities."
            echo "Removing wrong configuration from .config"
            rm -Rf .config/tabbed
            rm -Rf .config/surf
            rm -Rf .config/st
            rm -Rf .config/dwm
            rm -Rf .config/dwmblocks
            rm -Rf .config/dmenu
            rm -Rf .config/slock
            echo "Try Again."
            ;;
	    [nN])
            echo "Aborting"
            break
	       		;;
	    *)
            echo "Invalid input, try again"
            ;;
	esac
done

echo "Restoring original icanon tty settings"
stty "$saved_tty_settings"
